# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gettext_test_log}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2011-09-23}
  s.email = %q{grosser.michael@gmail.com}
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "gettext_test_log.gemspec",
    "init.rb",
    "lib/gettext_test_log.rb",
    "lib/gettext_test_log/fast_gettext_stub.rb",
    "spec/gettext_test_log_spec.rb",
    "spec/spec_helper.rb",
    "tasks/gettext_test_log.rake"
  ]
  s.homepage = %q{http://github.com/grosser/gettext_test_log}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Logs all gettext translations during test execution, to a GetText readable format}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

